### ISSUE TITLE
How to run an example?

### ISSUE THREAD

**Issue by littleggghost** [dhkim0821/IJRR_WBLC#1]
Hi, kim
Thanks for your share!
Could you add some instructions that let robots walk? Because after compile and run ./simulation_nao, the simulation environment was started but the robot just stand statically.
Thanks in advance!

**Comment by dhkim0821** [comment]
The simulation starts when you press the keyboard button 'p'. 

By the way, currently, there is no locomotion controller for NAO, but you can run other systems (mercury, Draco, atlas, valkyrie) to see the walking controller.

**Comment by littleggghost** [comment]
Thanks for your rapid reply!That works. 
I run it and find that simulation can only run on one core, could it use multi cores of cpu for speed?

**Comment by littleggghost** [comment]
Hi, @dhkim0821 , could you give me your email? I want to discuss more questions with you.
Mine is zhangygdyx@126.com

**Comment by littleggghost** [comment]
Hi,&nbsp;dhkim&nbsp;


Sorry for this email cause this the only way I can contact you.&nbsp;
Could you give me your own email? I want to discuss more questions with you.&nbsp;


yangguang Zhang
